# Generated by Django 4.2.3 on 2023-07-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='my_card',
            field=models.IntegerField(default=0),
        ),
    ]
