# Generated by Django 4.2.3 on 2023-07-21 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='my_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.player'),
        ),
    ]
