# Generated by Django 4.2.3 on 2023-07-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
    ]
