# Generated by Django 4.2.3 on 2023-07-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20230721_1448'),
        ('games', '0003_alter_game_my_card'),
    ]

    operations = [
    ]
